import { User } from 'src/models';

export class UserState extends User {}

//action to reducer
export const ACTION_SET_USER_PROFILE = 'ACTION_SET_USER_PROFILE';
export const ACTION_CLEAR_USER_PROFILE = 'ACTION_CLEAR_USER_PROFILE';
//action to reducer
export const SET_USER_WORKSPACE_ACTION = 'SET_USER_WORKSPACE_ACTION';
export const CLEAR_USER_WORKSPACE_ACTION = 'CLEAR_USER_WORKSPACE_ACTION';
//actions for middleware
export const USER_INVALID_TOKEN = 'USER_INVALID_TOKEN';
export const VALIDATE_USER_TOKEN = 'VALIDATE_USER_TOKEN';
export const USER_REQUEST_LOGIN = 'USER_REQUEST_LOGIN';

export const REQUEST_LOGIN_ACTION = 'REQUEST_LOGIN_ACTION';
export const REQUEST_LOGOUT_ACTION = 'REQUEST_LOGOUT_ACTION';
export const REQUEST_VALIDATE_ACCESS_TOKEN = 'REQUEST_VALIDATE_ACCESS_TOKEN';
export const REQUEST_REGISTER_ACTION = 'REQUEST_REGISTER_ACTION';
export const FETCH_USER_ACTION = 'FETCH_USER_ACTION';

export const KEY_ACCESS_TOKEN = 'KEY_ACCESS_TOKEN';
