export enum RouteName {
    INTRO = 'INTRO',
    REGISTER = 'REGISTER',
    LOGIN = 'LOGIN',
    FORGOT_PASSWORD = 'FORGOT_PASSWORD',
    RESET_PASSWORD = 'RESET_PASSWORD',
    JOINING = 'JOINING',
    HOME = 'HOME',
    HOME_OFFICE = 'HOME_OFFICE',
    HOME_PROFILE = 'HOME_PROFILE',
    SWITCH_WORKSPACE = 'SWITCH_WORKSPACE',
    NEW_PASSWORD = 'NEW_PASSWORD',
    UPDATE_PROFILE = 'UPDATE_PROFILE',
    // DeepLink Screen
    DEEPLINK_WORKSPACE_INVITATION = 'DEEPLINK_WORKSPACE_INVITATION',
    DEEPLINK_REGISTER = 'DEEPLINK_REGISTER',
}
