export enum RouteName {
  INTRO = 'INTRO',
  REGISTER = 'REGISTER',
  LOGIN = 'LOGIN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  RESET_PASSWORD = 'RESET_PASSWORD',
  JOINING = 'JOINING',
  HOME = 'HOME',
  HOME_OFFICE = 'HOME_OFFICE',
  HOME_DEVICES = 'HOME_DEVICES',
  HOME_PROFILE = 'HOME_PROFILE',

}
